### ISSUE TITLE
Not able to compile under Fedora 34

### ISSUE THREAD

**Issue by gapf2010** [wseemann/RPListening#1]
Hi!

I am trying to compile this under Fedora 34 using ffmpeg 4.4.2 and the latest Oracle 11 JDK installed from RPM. There are no other java versions instaled on my machine that can create a conflict, but it's failing with the following error:

`
[gpulido@fedora RPListening]$ ./gradlew customFatJar
Downloading https://services.gradle.org/distributions/gradle-6.3-bin.zip
.........10%..........20%..........30%.........40%..........50%..........60%.........70%..........80%..........90%..........100%

Welcome to Gradle 6.3!

Here are the highlights of this release:
 - Java 14 support
 - Improved error messages for unexpected failures

For more details see https://docs.gradle.org/6.3/release-notes.html

Starting a Gradle Daemon (subsequent builds will be faster)

> Task :compileKotlin FAILED
w: Runtime JAR files in the classpath should have the same version. These files were found in the classpath:
    /home/gpulido/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib-jdk8/1.5.10/3f4af7aff21c4ec46e3cdd645639d0a63a68d3d0/kotlin-stdlib-jdk8-1.5.10.jar (version 1.5)
    /home/gpulido/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib-jdk7/1.5.10/c49d0703d16c6cb1526cc07b9b46486da1dd8a60/kotlin-stdlib-jdk7-1.5.10.jar (version 1.5)
    /home/gpulido/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-reflect/1.3.61/2e07c9a84c9e118efb70eede7e579fd663932122/kotlin-reflect-1.3.61.jar (version 1.3)
    /home/gpulido/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib/1.5.10/da6a904b132f0402fa4d79169a3c1770598d4702/kotlin-stdlib-1.5.10.jar (version 1.5)
    /home/gpulido/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib-common/1.5.10/6b84d926e28493be69daf673e40076f89492ef7/kotlin-stdlib-common-1.5.10.jar (version 1.5)
w: Consider providing an explicit dependency on kotlin-reflect 1.5 to prevent strange errors
w: Some runtime JAR files in the classpath have an incompatible version. Consider removing them from the classpath
e: Supertypes of the following classes cannot be resolved. Please make sure you have the required dependencies in the classpath:
    class tornadofx.UIComponent, unresolved supertypes: javafx.event.EventTarget
    class tornadofx.App, unresolved supertypes: javafx.application.Application
Adding -Xextended-compiler-checks argument might provide additional information.

e: /media/packages/rpm/SOURCES/RPListening/RPListening/src/main/kotlin/wseemann/media/rplistening/ui/MainView.kt: (3, 8): Unresolved reference: javafx
e: /media/packages/rpm/SOURCES/RPListening/RPListening/src/main/kotlin/wseemann/media/rplistening/ui/MainView.kt: (4, 8): Unresolved reference: javafx
e: /media/packages/rpm/SOURCES/RPListening/RPListening/src/main/kotlin/wseemann/media/rplistening/ui/MainView.kt: (6, 8): Unresolved reference: javafx
e: /media/packages/rpm/SOURCES/RPListening/RPListening/src/main/kotlin/wseemann/media/rplistening/ui/MainView.kt: (7, 8): Unresolved reference: javafx
e: /media/packages/rpm/SOURCES/RPListening/RPListening/src/main/kotlin/wseemann/media/rplistening/ui/MainView.kt: (8, 8): Unresolved reference: javafx
e: /media/packages/rpm/SOURCES/RPListening/RPListening/src/main/kotlin/wseemann/media/rplistening/ui/MainView.kt: (9, 8): Unresolved reference: javafx
e: /media/packages/rpm/SOURCES/RPListening/RPListening/src/main/kotlin/wseemann/media/rplistening/ui/MainView.kt: (10, 8): Unresolved reference: javafx
e: /media/packages/rpm/SOURCES/RPListening/RPListening/src/main/kotlin/wseemann/media/rplistening/ui/MainView.kt: (11, 8): Unresolved reference: javafx
e: /media/packages/rpm/SOURCES/RPListening/RPListening/src/main/kotlin/wseemann/media/rplistening/ui/MainView.kt: (12, 8): Unresolved reference: javafx
e: /media/packages/rpm/SOURCES/RPListening/RPListening/src/main/kotlin/wseemann/media/rplistening/ui/MainView.kt: (13, 8): Unresolved reference: javafx
e: /media/packages/rpm/SOURCES/RPListening/RPListening/src/main/kotlin/wseemann/media/rplistening/ui/MainView.kt: (17, 1): Cannot access 'javafx.event.EventTarget' which is a supertype of 'wseemann.media.rplistening.ui.MyView'. Check your module classpath for missing or conflicting dependencies
e: /media/packages/rpm/SOURCES/RPListening/RPListening/src/main/kotlin/wseemann/media/rplistening/ui/MainView.kt: (17, 15): Cannot access class 'javafx.scene.Node'. Check your module classpath for missing or conflicting dependencies
e: /media/packages/rpm/SOURCES/RPListening/RPListening/src/main/kotlin/wseemann/media/rplistening/ui/MainView.kt: (21, 27): Unresolved reference: Label
e: /media/packages/rpm/SOURCES/RPListening/RPListening/src/main/kotlin/wseemann/media/rplistening/ui/MainView.kt: (21, 36): Not enough information to infer type variable T
e: /media/packages/rpm/SOURCES/RPListening/RPListening/src/main/kotlin/wseemann/media/rplistening/ui/MainView.kt: (21, 36): Property delegate must have a 'getValue(MyView, KProperty<*>)' method. None of the following functions is suitable: 
public abstract operator fun getValue(thisRef: Any?, property: KProperty<*>): ??? defined in tornadofx.SingleAssign
e: /media/packages/rpm/SOURCES/RPListening/RPListening/src/main/kotlin/wseemann/media/rplistening/ui/MainView.kt: (21, 36): Property delegate must have a 'setValue(MyView, KProperty<*>, [ERROR : Label])' method. None of the following functions is suitable: 
public abstract operator fun setValue(thisRef: Any?, property: KProperty<*>, value: ???): Unit defined in tornadofx.SingleAssign
e: /media/packages/rpm/SOURCES/RPListening/RPListening/src/main/kotlin/wseemann/media/rplistening/ui/MainView.kt: (22, 31): Unresolved reference: TextField
e: /media/packages/rpm/SOURCES/RPListening/RPListening/src/main/kotlin/wseemann/media/rplistening/ui/MainView.kt: (22, 44): Not enough information to infer type variable T
e: /media/packages/rpm/SOURCES/RPListening/RPListening/src/main/kotlin/wseemann/media/rplistening/ui/MainView.kt: (22, 44): Property delegate must have a 'getValue(MyView, KProperty<*>)' method. None of the following functions is suitable: 
public abstract operator fun getValue(thisRef: Any?, property: KProperty<*>): ??? defined in tornadofx.SingleAssign
e: /media/packages/rpm/SOURCES/RPListening/RPListening/src/main/kotlin/wseemann/media/rplistening/ui/MainView.kt: (22, 44): Property delegate must have a 'setValue(MyView, KProperty<*>, [ERROR : TextField])' method. None of the following functions is suitable: 
public abstract operator fun setValue(thisRef: Any?, property: KProperty<*>, value: ???): Unit defined in tornadofx.SingleAssign
e: /media/packages/rpm/SOURCES/RPListening/RPListening/src/main/kotlin/wseemann/media/rplistening/ui/MainView.kt: (23, 27): Unresolved reference: Label
e: /media/packages/rpm/SOURCES/RPListening/RPListening/src/main/kotlin/wseemann/media/rplistening/ui/MainView.kt: (23, 36): Not enough information to infer type variable T
e: /media/packages/rpm/SOURCES/RPListening/RPListening/src/main/kotlin/wseemann/media/rplistening/ui/MainView.kt: (23, 36): Property delegate must have a 'getValue(MyView, KProperty<*>)' method. None of the following functions is suitable: 
public abstract operator fun getValue(thisRef: Any?, property: KProperty<*>): ??? defined in tornadofx.SingleAssign
e: /media/packages/rpm/SOURCES/RPListening/RPListening/src/main/kotlin/wseemann/media/rplistening/ui/MainView.kt: (23, 36): Property delegate must have a 'setValue(MyView, KProperty<*>, [ERROR : Label])' method. None of the following functions is suitable: 
public abstract operator fun setValue(thisRef: Any?, property: KProperty<*>, value: ???): Unit defined in tornadofx.SingleAssign
e: /media/packages/rpm/SOURCES/RPListening/RPListening/src/main/kotlin/wseemann/media/rplistening/ui/MainView.kt: (25, 27): Unresolved reference: Button
e: /media/packages/rpm/SOURCES/RPListening/RPListening/src/main/kotlin/wseemann/media/rplistening/ui/MainView.kt: (25, 37): Not enough information to infer type variable T
e: /media/packages/rpm/SOURCES/RPListening/RPListening/src/main/kotlin/wseemann/media/rplistening/ui/MainView.kt: (25, 37): Property delegate must have a 'getValue(MyView, KProperty<*>)' method. None of the following functions is suitable: 
public abstract operator fun getValue(thisRef: Any?, property: KProperty<*>): ??? defined in tornadofx.SingleAssign
e: /media/packages/rpm/SOURCES/RPListening/RPListening/src/main/kotlin/wseemann/media/rplistening/ui/MainView.kt: (25, 37): Property delegate must have a 'setValue(MyView, KProperty<*>, [ERROR : Button])' method. None of the following functions is suitable: 
public abstract operator fun setValue(thisRef: Any?, property: KProperty<*>, value: ???): Unit defined in tornadofx.SingleAssign
e: /media/packages/rpm/SOURCES/RPListening/RPListening/src/main/kotlin/wseemann/media/rplistening/ui/MainView.kt: (26, 26): Unresolved reference: Button
e: /media/packages/rpm/SOURCES/RPListening/RPListening/src/main/kotlin/wseemann/media/rplistening/ui/MainView.kt: (26, 36): Not enough information to infer type variable T
e: /media/packages/rpm/SOURCES/RPListening/RPListening/src/main/kotlin/wseemann/media/rplistening/ui/MainView.kt: (26, 36): Property delegate must have a 'getValue(MyView, KProperty<*>)' method. None of the following functions is suitable: 
public abstract operator fun getValue(thisRef: Any?, property: KProperty<*>): ??? defined in tornadofx.SingleAssign
e: /media/packages/rpm/SOURCES/RPListening/RPListening/src/main/kotlin/wseemann/media/rplistening/ui/MainView.kt: (26, 36): Property delegate must have a 'setValue(MyView, KProperty<*>, [ERROR : Button])' method. None of the following functions is suitable: 
public abstract operator fun setValue(thisRef: Any?, property: KProperty<*>, value: ???): Unit defined in tornadofx.SingleAssign
e: /media/packages/rpm/SOURCES/RPListening/RPListening/src/main/kotlin/wseemann/media/rplistening/ui/MainView.kt: (28, 22): Unresolved reference. None of the following candidates is applicable because of receiver type mismatch: 
public fun EventTarget.form(op: Form.() -> Unit = ...): Form defined in tornadofx
e: /media/packages/rpm/SOURCES/RPListening/RPListening/src/main/kotlin/wseemann/media/rplistening/ui/MainView.kt: (31, 3): Not enough information to infer type variable R
e: /media/packages/rpm/SOURCES/RPListening/RPListening/src/main/kotlin/wseemann/media/rplistening/ui/MainView.kt: (31, 8): Cannot access 'javafx.event.EventTarget' which is a supertype of 'wseemann.media.rplistening.ui.MyView'. Check your module classpath for missing or conflicting dependencies
e: /media/packages/rpm/SOURCES/RPListening/RPListening/src/main/kotlin/wseemann/media/rplistening/ui/MainView.kt: (33, 4): Variable expected
e: /media/packages/rpm/SOURCES/RPListening/RPListening/src/main/kotlin/wseemann/media/rplistening/ui/MainView.kt: (35, 4): Variable expected
e: /media/packages/rpm/SOURCES/RPListening/RPListening/src/main/kotlin/wseemann/media/rplistening/ui/MainView.kt: (45, 15): Function '<ERROR FUNCTION>' should return Unit to be used by corresponding operator '+='
e: /media/packages/rpm/SOURCES/RPListening/RPListening/src/main/kotlin/wseemann/media/rplistening/ui/MainView.kt: (46, 15): Function '<ERROR FUNCTION>' should return Unit to be used by corresponding operator '+='
e: /media/packages/rpm/SOURCES/RPListening/RPListening/src/main/kotlin/wseemann/media/rplistening/ui/MainView.kt: (49, 4): Variable expected
e: /media/packages/rpm/SOURCES/RPListening/RPListening/src/main/kotlin/wseemann/media/rplistening/ui/MainView.kt: (55, 15): Function '<ERROR FUNCTION>' should return Unit to be used by corresponding operator '+='
e: /media/packages/rpm/SOURCES/RPListening/RPListening/src/main/kotlin/wseemann/media/rplistening/ui/MainView.kt: (58, 4): Variable expected
e: /media/packages/rpm/SOURCES/RPListening/RPListening/src/main/kotlin/wseemann/media/rplistening/ui/MainView.kt: (71, 9): Variable expected
e: /media/packages/rpm/SOURCES/RPListening/RPListening/src/main/kotlin/wseemann/media/rplistening/ui/MainView.kt: (79, 9): Variable expected
e: /media/packages/rpm/SOURCES/RPListening/RPListening/src/main/kotlin/wseemann/media/rplistening/ui/MainView.kt: (93, 4): Variable expected
e: /media/packages/rpm/SOURCES/RPListening/RPListening/src/main/kotlin/wseemann/media/rplistening/ui/MainView.kt: (108, 15): Function '<ERROR FUNCTION>' should return Unit to be used by corresponding operator '+='
e: /media/packages/rpm/SOURCES/RPListening/RPListening/src/main/kotlin/wseemann/media/rplistening/ui/MainView.kt: (109, 15): Function '<ERROR FUNCTION>' should return Unit to be used by corresponding operator '+='
e: /media/packages/rpm/SOURCES/RPListening/RPListening/src/main/kotlin/wseemann/media/rplistening/ui/MainView.kt: (111, 9): Function '<ERROR FUNCTION>' should return Unit to be used by corresponding operator '+='
e: /media/packages/rpm/SOURCES/RPListening/RPListening/src/main/kotlin/wseemann/media/rplistening/ui/MainView.kt: (112, 9): Function '<ERROR FUNCTION>' should return Unit to be used by corresponding operator '+='
e: /media/packages/rpm/SOURCES/RPListening/RPListening/src/main/kotlin/wseemann/media/rplistening/ui/MainView.kt: (113, 9): Function '<ERROR FUNCTION>' should return Unit to be used by corresponding operator '+='
e: /media/packages/rpm/SOURCES/RPListening/RPListening/src/main/kotlin/wseemann/media/rplistening/ui/RPListeningApp.kt: (5, 1): Cannot access 'javafx.application.Application' which is a supertype of 'wseemann.media.rplistening.ui.RPListeningApp'. Check your module classpath for missing or conflicting dependencies

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileKotlin'.
> Compilation error. See log for more details

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.3/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 1m 26s
1 actionable task: 1 executed
[gpulido@fedora RPListening]$ 
`

Thanks!

**Comment by wseemann** [comment]
@gapf2010 Thanks for creating this issue. I recently updated the project to incorporate a GUI using JavaFX and forgot to include the jars in the project. If you do a fresh checkout of the code you should be able to use the same build steps as before without an issue. Let me know if this doesn't work.

**Comment by gapf2010** [comment]
Hello, thanks for the quick response. In fact I could compile successfully now, however some warning are thrown:

> Task :compileKotlin
w: Runtime JAR files in the classpath should have the same version. These files were found in the classpath:
    /home/gpulido/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib-jdk8/1.5.10/3f4af7aff21c4ec46e3cdd645639d0a63a68d3d0/kotlin-stdlib-jdk8-1.5.10.jar (version 1.5)
    /home/gpulido/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib-jdk7/1.5.10/c49d0703d16c6cb1526cc07b9b46486da1dd8a60/kotlin-stdlib-jdk7-1.5.10.jar (version 1.5)
    /home/gpulido/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-reflect/1.3.61/2e07c9a84c9e118efb70eede7e579fd663932122/kotlin-reflect-1.3.61.jar (version 1.3)
    /home/gpulido/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib/1.5.10/da6a904b132f0402fa4d79169a3c1770598d4702/kotlin-stdlib-1.5.10.jar (version 1.5)
    /home/gpulido/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib-common/1.5.10/6b84d926e28493be69daf673e40076f89492ef7/kotlin-stdlib-common-1.5.10.jar (version 1.5)
w: Consider providing an explicit dependency on kotlin-reflect 1.5 to prevent strange errors
w: Some runtime JAR files in the classpath have an incompatible version. Consider removing them from the classpath
w: /media/packages/rpm/SOURCES/RPListening/RPListening/src/main/kotlin/wseemann/media/rplistening/ui/MainView.kt: (62, 49): Parameter 'obs' is never used, could be renamed to _
w: /media/packages/rpm/SOURCES/RPListening/RPListening/src/main/kotlin/wseemann/media/rplistening/ui/MainView.kt: (62, 54): Parameter 'old' is never used, could be renamed to _
w: /media/packages/rpm/SOURCES/RPListening/RPListening/src/main/kotlin/wseemann/media/rplistening/ui/MainView.kt: (82, 49): Parameter 'obs' is never used, could be renamed to _
w: /media/packages/rpm/SOURCES/RPListening/RPListening/src/main/kotlin/wseemann/media/rplistening/ui/MainView.kt: (82, 54): Parameter 'old' is never used, could be renamed to _

> Task :compileJava
Note: /media/packages/rpm/SOURCES/RPListening/RPListening/src/main/java/wseemann/media/rplistening/protocol/PrivateListeningSession.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: /media/packages/rpm/SOURCES/RPListening/RPListening/src/main/java/wseemann/media/rplistening/protocol/PrivateListeningSession.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
<==-----------> 20% EXECUTING [3m 49s]

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.3/userguide/command_line_interface.html#sec:command_line_warnings

Are those normal?

**Comment by wseemann** [comment]
Yep, those are normal, just some unused variable warnings which should get cleaned up soon!

**Comment by wseemann** [comment]
More importantly, did the code work for you once you compiled it?

**Comment by gapf2010** [comment]
> More importantly, did the code work for you once you compiled it?

Yes, it works correctly. I compiled it on a fedora 34 test machine using latest Oracle JDK 11, running it currently on another Fedora 34 machine using OpenJDK:

[gpulido@starscream ~]$ java -version
openjdk version "11.0.11" 2021-04-20
OpenJDK Runtime Environment 18.9 (build 11.0.11+9)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.11+9, mixed mode, sharing)
[gpulido@starscream ~]$ 

The -d option does not work though, it just hangs with a black screen. I assume it is because you are trying to use SSDP to find the Roku, but that does not seem to work anymore (My roku runs the latest version 10 OS). Even when I try the test suggested here: https://developer.roku.com/en-ca/docs/developer-program/debugging/external-control-api.md my Roku is not found, however I know SSDP works on my network because my router is found (it uses UPnP. Official Roku app on the mobile phone finds my Roku though, but no other app or SSDP clients seem to detect it at all.

**Comment by wseemann** [comment]
Awesome, thanks for the response! I'm going to close this ticket out just for housekeeping. If you need anything else let me know. I'll be updating this app a lot in the upcoming weeks and adding a GUI as well!
